# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6946382509d8eefc668c753aa67f1cc32e4c6cfb54b87e3797b676365fad4dde61fec8921cdedcbc3415c504c321a2f6be561ece910126b76b88ed47f27cacc5

test:
  secret_key_base: 47e2bcdc354687f78b5fadc7e4239a7414c7c728bc5b85231d92c4e3174d6b6907690d7d2a5113c258342749333fe62578c8e7c23084ea2dca514a0c3546919c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
